CREATE TABLE aguardo_produto( 
      system_unit_id integer    NOT NULL , 
      system_users_id integer    NOT NULL , 
      id  integer generated by default as identity     NOT NULL , 
      repres_id integer    NOT NULL , 
      ap_item_id integer    NOT NULL , 
      quantidade float   , 
      status char  (1)    DEFAULT 'A' , 
      cod_clifor char  (7)   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE ap_cidade( 
      id  integer generated by default as identity     NOT NULL , 
      nome varchar  (255)   , 
      estado_id integer   , 
      cod_cidade varchar  (5)   , 
      latitude float   , 
      longitude float   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE ap_estado( 
      id  integer generated by default as identity     NOT NULL , 
      cod_estado varchar  (10)   , 
      nome varchar  (255)   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE ap_familia_comercial( 
      system_unit_id integer    NOT NULL , 
      id  integer generated by default as identity     NOT NULL , 
      descricao varchar  (255)    NOT NULL , 
      cod_fmcomercial char  (8)    NOT NULL , 
 PRIMARY KEY (id)) ; 

CREATE TABLE ap_familia_industrial( 
      system_unit_id integer    NOT NULL , 
      id  integer generated by default as identity     NOT NULL , 
      descricao varchar  (255)    NOT NULL , 
      cod_fmindustrial char  (8)    NOT NULL , 
 PRIMARY KEY (id)) ; 

CREATE TABLE ap_grupo_cliente( 
      id integer    NOT NULL , 
      cod_grpcliente varchar  (10)   , 
      descricao varchar  (255)   , 
      pontuacao integer   , 
      valor_inicial float   , 
      valor_final float   , 
      system_unit_id integer    NOT NULL , 
 PRIMARY KEY (id)) ; 

CREATE TABLE ap_grupo_estoque( 
      system_unit_id integer    NOT NULL , 
      id  integer generated by default as identity     NOT NULL , 
      cod_grupoestoque varchar  (8)    NOT NULL , 
      descricao varchar  (255)    NOT NULL , 
      sequencia_exibicao integer   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE ap_item( 
      system_unit_id integer    NOT NULL , 
      id  integer generated by default as identity     NOT NULL , 
      cod_item char  (10)   , 
      cod_clifor char  (7)   , 
      subgrupo_estoque_id integer   , 
      grupo_estoque_id integer   , 
      familia_comercial_id integer   , 
      familia_industrial_id integer   , 
      codigo char  (20)   , 
      descricao varchar  (100)   , 
      cod_unidade char  (6)   , 
      ativo char  (1)   , 
      ap_fm_industrial_id_teste char  (10)   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE ap_representante( 
      system_unit_id integer    NOT NULL , 
      id  integer generated by default as identity     NOT NULL , 
      cod_repres char  (7)   , 
      razao varchar  (255)   , 
      fantasia varchar  (255)   , 
      ativo char  (1)   , 
      system_users_id integer   , 
      email varchar  (255)   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE ap_subgrupo_estoque( 
      system_unit_id integer    NOT NULL , 
      id  integer generated by default as identity     NOT NULL , 
      grupo_estoque_id integer   , 
      cod_subgrupoestoque char  (8)    NOT NULL , 
      cod_grupoestoque varchar  (15)   , 
      descricao varchar  (255)    NOT NULL , 
 PRIMARY KEY (id)) ; 

CREATE TABLE ap_tabela_preco( 
      id  integer generated by default as identity     NOT NULL , 
      cod_tabelapreco char  (20)   , 
      descricao varchar  (100)   , 
      ativo char  (1)   , 
      system_unit_id integer    NOT NULL , 
 PRIMARY KEY (id)) ; 

CREATE TABLE campanha( 
      system_unit_id integer    NOT NULL , 
      ap_tabela_preco_id integer    NOT NULL , 
      campanha_tipo_id integer    NOT NULL , 
      id  integer generated by default as identity     NOT NULL , 
      descricao varchar  (255)   , 
      data_inicial timestamp   , 
      data_final timestamp   , 
      status integer    DEFAULT 1 , 
      valor_unitario_min float  (15,2)   , 
      min float   , 
      qtde float   , 
      painel integer   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE campanha_fechamento( 
      id  integer generated by default as identity     NOT NULL , 
      premio float   , 
      campanha_id integer    NOT NULL , 
      ap_representante_id integer    NOT NULL , 
      alcancou_quantidade char   , 
      alcancou_ranking char   , 
      quantidade_total float   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE campanha_item( 
      id  integer generated by default as identity     NOT NULL , 
      campanha_id integer    NOT NULL , 
      cod_item blob sub_type 1    NOT NULL , 
 PRIMARY KEY (id)) ; 

CREATE TABLE campanha_premio( 
      campanha_id integer    NOT NULL , 
      comparador_id integer    NOT NULL , 
      id  integer generated by default as identity     NOT NULL , 
      dado_0 float   , 
      dado_1 float   , 
      premio varchar  (255)    NOT NULL , 
      tipo_valor integer   , 
      alvo_valor char  (1)   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE campanha_repres( 
      id  integer generated by default as identity     NOT NULL , 
      campanha_id integer    NOT NULL , 
      repres_id integer    NOT NULL , 
      quantidade float   , 
      valor float   , 
      premio float   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE campanha_tabela_preco( 
      id  integer generated by default as identity     NOT NULL , 
      ap_tabela_preco_id integer    NOT NULL , 
      campanha_id integer    NOT NULL , 
      fazparte char   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE campanha_tipo( 
      id  integer generated by default as identity     NOT NULL , 
      nome varchar  (255)   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE cep_coordenadas( 
      id  integer generated by default as identity     NOT NULL , 
      cep varchar  (10)   , 
      latitude float   , 
      longitude float   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE comparador( 
      id  integer generated by default as identity     NOT NULL , 
      descricao varchar  (255)    NOT NULL , 
      operador varchar  (255)    NOT NULL , 
 PRIMARY KEY (id)) ; 

CREATE TABLE credito_cliente( 
      id  integer generated by default as identity     NOT NULL , 
      cod_clifor varchar  (7)   , 
      valor_total float  (15,2)   , 
      media_por_pedido float  (15,2)   , 
      razao_clifor varchar  (255)   , 
      periodo_inicio timestamp   , 
      periodo_fim timestamp   , 
      quantidade_notas integer   , 
      data_processamento timestamp    DEFAULT now() , 
      historico_cli_id integer   , 
      credito_cliente_cadastro_id integer    NOT NULL , 
 PRIMARY KEY (id)) ; 

CREATE TABLE credito_cliente_cadastro( 
      id  integer generated by default as identity    , 
      descricao blob sub_type 1    NOT NULL , 
      periodo_inicio timestamp    NOT NULL , 
      periodo_fim timestamp    NOT NULL , 
      data_criacao timestamp    DEFAULT now() , 
      status integer    DEFAULT 1 , 
 PRIMARY KEY (id)) ; 

CREATE TABLE grupo( 
      system_unit_id integer    NOT NULL , 
      id  integer generated by default as identity     NOT NULL , 
      cod_grupoestoque char  (8)    NOT NULL , 
      descricao varchar  (255)    NOT NULL , 
 PRIMARY KEY (id)) ; 

CREATE TABLE historico_cli_repres( 
      system_unit_id integer    NOT NULL , 
      id  integer generated by default as identity     NOT NULL , 
      ano integer   , 
      mes integer   , 
      cod_clifor char  (7)   , 
      razao_clifor varchar  (255)   , 
      dt_cadastro timestamp   , 
      ap_cidade_id integer   , 
      grupo_id integer   , 
      repres_id integer   , 
      ativo char  (1)   , 
      agente_regular_anp varchar  (10)   , 
      tipo varchar  (255)   , 
      prospeccao char  (1)   , 
      cod_estado char  (2)   , 
      filial char  (1)   , 
      cod_principal varchar  (7)   , 
      tipo_pessoa char  (1)   , 
      rota blob sub_type 1   , 
      grupo_empresarial char  (1)   , 
      latitude float   , 
      longitude float   , 
      cep varchar  (10)   , 
      dt_atualizacao timestamp   , 
      dt_change timestamp   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE historico_venda( 
      meta_id integer   , 
      system_unit_id integer    NOT NULL , 
      id  integer generated by default as identity     NOT NULL , 
      data_emissao timestamp   , 
      data_cadastro timestamp   , 
      nro char  (10)   , 
      tipo_pessoa char  (1)   , 
      cod_clifor char  (10)   , 
      razao varchar  (255)   , 
      agente blob sub_type 1   , 
      repres_id integer   , 
      grupo_cliente_id integer   , 
      cidade_id integer   , 
      estado_id integer   , 
      rota blob sub_type 1   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE historico_venda_item( 
      empresa varchar  (255)   , 
      venda_id integer    NOT NULL , 
      id  integer generated by default as identity     NOT NULL , 
      cod_item blob sub_type 1   , 
      descricao varchar  (255)   , 
      grupo_estoque_id integer   , 
      subgrupo_estoque_id integer   , 
      familia_comercial_id integer   , 
      familia_industrial_id integer   , 
      quantidade float   , 
      valor_unitario float   , 
      valor_mercadoria float   , 
      perc_desconto float   , 
      valor_desconto float   , 
      valor_total float   , 
      sequencia integer   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE log_crontab( 
      system_unit_id integer    NOT NULL , 
      id  integer generated by default as identity     NOT NULL , 
      classe blob sub_type 1    NOT NULL , 
      metodo blob sub_type 1   , 
      data_hora timestamp   , 
      status integer   , 
      mensagem blob sub_type 1   , 
      observacao blob sub_type 1   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE meta( 
      system_unit_id integer    NOT NULL , 
      id  integer generated by default as identity     NOT NULL , 
      ano integer   , 
      mes integer   , 
      data_inicial timestamp   , 
      data_final timestamp   , 
      data_abertura timestamp   , 
      data_entrega timestamp   , 
      data_me timestamp   , 
      dias_uteis integer   , 
      feriados integer   , 
      dias_disponiveis integer   , 
      status integer    DEFAULT 1 , 
      mes_ano varchar  (255)   , 
      limite_import integer   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE meta_fechamento( 
      id  integer generated by default as identity     NOT NULL , 
      meta_id integer    NOT NULL , 
      meta_repres_id integer    NOT NULL , 
      repres_id integer    NOT NULL , 
      faturamento_total float   , 
      faturamento_cortina float   , 
      faturamento_mostruario float   , 
      faturamento_prospeccao float   , 
      faturamento_reativacao float   , 
      faturamento_prosp_reat float   , 
      percentual_import float   , 
      percentual_persianas float   , 
      alcancou_meta char  (1)   , 
      alcancou_super_meta char  (1)   , 
      alcancou_import char  (1)   , 
      alcancou_persianas char  (1)   , 
      alcancou_cortina_pronta char  (1)   , 
      alcancou_mostruario char  (1)   , 
      alcancou_prospeccao char  (1)   , 
      alcancou_reativacao char  (1)   , 
      alcancou_prosp_reat char  (1)   , 
      alcancou_site char  (1)   , 
      premio_cortina float   , 
      premio_mostruario float   , 
      premio_prospeccao float   , 
      premio_reativacao float   , 
      premio_site float   , 
      premio_prosp_reat float   , 
      comissao float   , 
      bonus_meta float   , 
      bonus_mini float   , 
      bonus_mini_pers float   , 
      bonus_mini_import float   , 
      st float   , 
      premio_estrategico float   , 
      site_porcentagem float   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE meta_feriado( 
      id  integer generated by default as identity     NOT NULL , 
      meta_id integer   , 
      data_feriado date   , 
      descricao varchar  (255)   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE meta_import( 
      system_unit_id integer    NOT NULL , 
      id  integer generated by default as identity     NOT NULL , 
      descricao varchar  (255)   , 
      data_inicial timestamp   , 
      data_final timestamp   , 
      status integer    DEFAULT 1 , 
      painel integer   , 
      ano integer   , 
      mes integer   , 
      ap_tabela_preco_id integer    NOT NULL , 
 PRIMARY KEY (id)) ; 

CREATE TABLE meta_import_fechamento( 
      id  integer generated by default as identity     NOT NULL , 
      meta_import_repres_id integer   , 
      qtd_total float  (15,2)   , 
      meta_import_id integer    NOT NULL , 
      ap_representante_id integer    NOT NULL , 
      percentual_qtd float  (15,2)   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE meta_import_item( 
      id  integer generated by default as identity     NOT NULL , 
      meta_import_id integer    NOT NULL , 
      cod_item blob sub_type 1   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE meta_import_repres( 
      id  integer generated by default as identity     NOT NULL , 
      qtd float  (15,2)   , 
      fantasia varchar  (255)   , 
      ap_representante_id integer   , 
      meta_import_id integer   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE meta_import_tabela_preco( 
      id  integer generated by default as identity     NOT NULL , 
      fazparte char  (1)   , 
      ap_tabela_preco_id integer    NOT NULL , 
      meta_import_id integer    NOT NULL , 
 PRIMARY KEY (id)) ; 

CREATE TABLE meta_repres( 
      id  integer generated by default as identity     NOT NULL , 
      meta_id integer   , 
      repres_id integer   , 
      fantasia varchar  (255)   , 
      valor_meta float  (15,2)   , 
      valor_super_meta float  (15,2)   , 
      valor_moc float  (15,2)   , 
      valor_cortina float  (15,2)   , 
      valor_mostruario float  (15,2)   , 
      valor_prospeccao float  (15,2)   , 
      valor_reativacao float  (15,2)   , 
      valor_prosp_reat float   , 
      perc_site float  (15,2)   , 
      perc_aprov_carteira float  (15,2)   , 
      perc_cliente_abaixo float  (15,2)   , 
      perc_fora_estado float  (15,2)   , 
      perc_import float   , 
      perc_persianas float   , 
      valor_import float   , 
      valor_persianas float   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE meta_trimestral( 
      id  integer generated by default as identity     NOT NULL , 
      descricao varchar  (255)    NOT NULL , 
      data_inicial date    NOT NULL , 
      data_final date   , 
      status integer    NOT NULL , 
 PRIMARY KEY (id)) ; 

CREATE TABLE meta_trimestral_repres( 
      id  integer generated by default as identity     NOT NULL , 
      meta_trimestral_id integer    NOT NULL , 
      ap_representante_id integer    NOT NULL , 
      valor float    NOT NULL , 
      pontuacao_inicial float   , 
      pontuacao_alvo float   , 
      pontuacao_atual float   , 
      fantasia varchar  (255)   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE mini_meta( 
      system_unit_id integer    NOT NULL , 
      id  integer generated by default as identity     NOT NULL , 
      mini_meta_tipo_id integer    NOT NULL , 
      ap_tabela_preco_id integer    NOT NULL , 
      painel integer   , 
      descricao varchar  (255)   , 
      ano integer   , 
      mes integer   , 
      data_inicial timestamp   , 
      data_final timestamp   , 
      status integer    DEFAULT 1 , 
      min float   , 
      qtde float   , 
      mes_ano varchar  (255)   , 
      valor_unitario_min float  (15,2)   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE mini_meta_fechamento( 
      id  integer generated by default as identity     NOT NULL , 
      mini_meta_id integer    NOT NULL , 
      ap_representante_id integer    NOT NULL , 
      alcancou_st char   , 
      quantidade_st float   , 
      premio_st float   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE mini_meta_item( 
      id  integer generated by default as identity     NOT NULL , 
      mini_meta_id integer    NOT NULL , 
      cod_item blob sub_type 1    NOT NULL , 
 PRIMARY KEY (id)) ; 

CREATE TABLE minimeta_tabela_preco( 
      id  integer generated by default as identity     NOT NULL , 
      ap_tabela_preco_id integer    NOT NULL , 
      mini_meta_id integer    NOT NULL , 
      fazparte char   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE mini_meta_tipo( 
      id  integer generated by default as identity     NOT NULL , 
      nome varchar  (255)    NOT NULL , 
 PRIMARY KEY (id)) ; 

CREATE TABLE planejamento_import( 
      id  integer generated by default as identity     NOT NULL , 
      qtd integer   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE planejamento_import_dias( 
      id  integer generated by default as identity     NOT NULL , 
      planejamento_import_id integer    NOT NULL , 
      dia integer   , 
      valido char  (1)   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE planejamento_import_excecao( 
      id  integer generated by default as identity     NOT NULL , 
      data date   , 
      planejamento_import_id integer    NOT NULL , 
      qtd integer   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE preferencia_sistema( 
      id  integer generated by default as identity     NOT NULL , 
      system_users_id integer    NOT NULL , 
      zoom integer    DEFAULT 100  NOT NULL , 
      data_criacao timestamp   , 
      criacao_user_id integer   , 
      data_modificacao timestamp   , 
      modificacao_user_id integer   , 
      menu_fixado integer    DEFAULT 0  NOT NULL , 
 PRIMARY KEY (id)) ; 

CREATE TABLE premio( 
      id  integer generated by default as identity     NOT NULL , 
      ano integer    NOT NULL , 
      mes integer    NOT NULL , 
      tipo_premio_id integer    NOT NULL , 
      obs blob sub_type 1   , 
      restricao char  (1)   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE premio_regra( 
      id  integer generated by default as identity     NOT NULL , 
      premio_id integer    NOT NULL , 
      comparador_id integer    NOT NULL , 
      dado_0 float    NOT NULL , 
      dado_1 float   , 
      bonus float    NOT NULL , 
      tipo_valor integer    NOT NULL , 
      alvo_valor char  (1)   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE regra_prospeccao( 
      system_unit_id integer    NOT NULL , 
      id  integer generated by default as identity     NOT NULL , 
      ano integer   , 
      mes integer   , 
      estado_op integer   , 
      filial_op integer   , 
      estado varchar  (255)   , 
      filial varchar  (255)   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE restricao_premio( 
      id  integer generated by default as identity     NOT NULL , 
      premio_id integer    NOT NULL , 
      ap_grupo_estoque_id integer    NOT NULL , 
      ap_subgrupo_estoque_id integer   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE system_group( 
      id integer    NOT NULL , 
      name blob sub_type 1    NOT NULL , 
      uuid varchar  (36)   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE system_group_program( 
      id integer    NOT NULL , 
      system_group_id integer    NOT NULL , 
      system_program_id integer    NOT NULL , 
      actions blob sub_type 1   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE system_preference( 
      id varchar  (255)    NOT NULL , 
      preference blob sub_type 1   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE system_program( 
      id integer    NOT NULL , 
      name blob sub_type 1    NOT NULL , 
      controller blob sub_type 1    NOT NULL , 
      actions blob sub_type 1   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE system_unit( 
      id integer    NOT NULL , 
      name blob sub_type 1    NOT NULL , 
      connection_name blob sub_type 1   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE system_user_group( 
      id integer    NOT NULL , 
      system_user_id integer    NOT NULL , 
      system_group_id integer    NOT NULL , 
 PRIMARY KEY (id)) ; 

CREATE TABLE system_user_program( 
      id integer    NOT NULL , 
      system_user_id integer    NOT NULL , 
      system_program_id integer    NOT NULL , 
 PRIMARY KEY (id)) ; 

CREATE TABLE system_users( 
      system_unit_id integer   , 
      id integer    NOT NULL , 
      name blob sub_type 1    NOT NULL , 
      login blob sub_type 1    NOT NULL , 
      password blob sub_type 1    NOT NULL , 
      email blob sub_type 1   , 
      frontpage_id integer   , 
      active char  (1)   , 
      accepted_term_policy_at blob sub_type 1   , 
      accepted_term_policy char  (1)   , 
      two_factor_enabled char  (1)    DEFAULT 'N' , 
      two_factor_type varchar  (100)   , 
      two_factor_secret varchar  (255)   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE system_user_unit( 
      id integer    NOT NULL , 
      system_user_id integer    NOT NULL , 
      system_unit_id integer    NOT NULL , 
 PRIMARY KEY (id)) ; 

CREATE TABLE tipo_premio( 
      id  integer generated by default as identity     NOT NULL , 
      descricao varchar  (255)    NOT NULL , 
      coluna varchar  (255)   , 
      seq integer   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE trimestre_cliente_atual( 
      id  integer generated by default as identity     NOT NULL , 
      meta_trimestral_id integer    NOT NULL , 
      data_insercao timestamp    NOT NULL , 
      cod_clifor char  (7)    NOT NULL , 
      razao_social varchar  (255)   , 
      dt_cadastro timestamp   , 
      grupo_id integer   , 
      repres_id integer   , 
      ativo char  (1)   , 
      reativacao varchar  (10)   , 
      tipo_pessoa char  (1)   , 
      filial char  (1)   , 
      cod_principal char  (7)   , 
      rota varchar  (255)   , 
      cidade_id integer   , 
      estado_id integer   , 
      mes_inicial integer   , 
      valor_total float   , 
      valor_mostruario float   , 
      valor_media float   , 
      valor_grupo float   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE trimestre_cliente_inicial( 
      id  integer generated by default as identity     NOT NULL , 
      meta_trimestral_id integer    NOT NULL , 
      data_insercao timestamp    NOT NULL , 
      cod_clifor char  (7)    NOT NULL , 
      razao_social varchar  (255)   , 
      dt_cadastro timestamp   , 
      grupo_id integer   , 
      repres_id integer   , 
      ativo char  (1)   , 
      reativacao varchar  (10)   , 
      tipo_pessoa char  (1)   , 
      filial char  (1)   , 
      cod_principal char  (7)   , 
      rota varchar  (255)   , 
      cidade_id integer   , 
      estado_id integer   , 
 PRIMARY KEY (id)) ; 

 
  
 ALTER TABLE aguardo_produto ADD CONSTRAINT fk_aguardo_produto_4 FOREIGN KEY (ap_item_id) references ap_item(id); 
ALTER TABLE aguardo_produto ADD CONSTRAINT fk_aguardando_produto_2 FOREIGN KEY (system_users_id) references system_users(id); 
ALTER TABLE aguardo_produto ADD CONSTRAINT fk_aguardo_produto_3 FOREIGN KEY (repres_id) references ap_representante(id); 
ALTER TABLE aguardo_produto ADD CONSTRAINT fk_aguardo_produto_4 FOREIGN KEY (system_unit_id) references system_unit(id); 
ALTER TABLE ap_cidade ADD CONSTRAINT fk_cidade_1 FOREIGN KEY (estado_id) references ap_estado(id); 
ALTER TABLE ap_familia_comercial ADD CONSTRAINT fk_ap_familia_comercial_1 FOREIGN KEY (system_unit_id) references system_unit(id); 
ALTER TABLE ap_familia_industrial ADD CONSTRAINT fk_ap_familia_industrial_1 FOREIGN KEY (system_unit_id) references system_unit(id); 
ALTER TABLE ap_grupo_cliente ADD CONSTRAINT fk_ap_grupo_cliente_1 FOREIGN KEY (system_unit_id) references system_unit(id); 
ALTER TABLE ap_grupo_estoque ADD CONSTRAINT fk_ap_grupo_estoque_1 FOREIGN KEY (system_unit_id) references system_unit(id); 
ALTER TABLE ap_item ADD CONSTRAINT fk_ap_item_1 FOREIGN KEY (subgrupo_estoque_id) references ap_subgrupo_estoque(id); 
ALTER TABLE ap_item ADD CONSTRAINT fk_ap_item_2 FOREIGN KEY (grupo_estoque_id) references ap_grupo_estoque(id); 
ALTER TABLE ap_item ADD CONSTRAINT fk_ap_item_3 FOREIGN KEY (familia_comercial_id) references ap_familia_comercial(id); 
ALTER TABLE ap_item ADD CONSTRAINT fk_ap_item_4 FOREIGN KEY (familia_industrial_id) references ap_familia_industrial(id); 
ALTER TABLE ap_item ADD CONSTRAINT fk_ap_item_5 FOREIGN KEY (system_unit_id) references system_unit(id); 
ALTER TABLE ap_representante ADD CONSTRAINT fk_ap_representante_2 FOREIGN KEY (system_users_id) references system_users(id); 
ALTER TABLE ap_representante ADD CONSTRAINT fk_ap_representante_2 FOREIGN KEY (system_unit_id) references system_unit(id); 
ALTER TABLE ap_subgrupo_estoque ADD CONSTRAINT fk_ap_subgrupo_estoque_1 FOREIGN KEY (grupo_estoque_id) references ap_grupo_estoque(id); 
ALTER TABLE ap_subgrupo_estoque ADD CONSTRAINT fk_ap_subgrupo_estoque_2 FOREIGN KEY (system_unit_id) references system_unit(id); 
ALTER TABLE ap_tabela_preco ADD CONSTRAINT fk_ap_tabela_preco_1 FOREIGN KEY (system_unit_id) references system_unit(id); 
ALTER TABLE campanha ADD CONSTRAINT fk_campanha_2 FOREIGN KEY (ap_tabela_preco_id) references ap_tabela_preco(id); 
ALTER TABLE campanha ADD CONSTRAINT fk_campanha_3 FOREIGN KEY (campanha_tipo_id) references campanha_tipo(id); 
ALTER TABLE campanha ADD CONSTRAINT fk_campanha_3 FOREIGN KEY (system_unit_id) references system_unit(id); 
ALTER TABLE campanha_fechamento ADD CONSTRAINT fk_campanha_fechamento_1 FOREIGN KEY (campanha_id) references campanha(id); 
ALTER TABLE campanha_fechamento ADD CONSTRAINT fk_campanha_fechamento_2 FOREIGN KEY (ap_representante_id) references ap_representante(id); 
ALTER TABLE campanha_item ADD CONSTRAINT campanha_item_6a85b1cbaec70 FOREIGN KEY (campanha_id) references campanha(id); 
ALTER TABLE campanha_premio ADD CONSTRAINT fk_campanha_premio_1 FOREIGN KEY (comparador_id) references comparador(id); 
ALTER TABLE campanha_premio ADD CONSTRAINT fk_campanha_premio_2 FOREIGN KEY (campanha_id) references campanha(id); 
ALTER TABLE campanha_repres ADD CONSTRAINT fk_campanha_repres_1 FOREIGN KEY (campanha_id) references campanha(id); 
ALTER TABLE campanha_repres ADD CONSTRAINT fk_campanha_repres_2 FOREIGN KEY (repres_id) references ap_representante(id); 
ALTER TABLE campanha_tabela_preco ADD CONSTRAINT fk_campanha_tabela_preco_1 FOREIGN KEY (ap_tabela_preco_id) references ap_tabela_preco(id); 
ALTER TABLE campanha_tabela_preco ADD CONSTRAINT fk_campanha_tabela_preco_2 FOREIGN KEY (campanha_id) references campanha(id); 
ALTER TABLE credito_cliente ADD CONSTRAINT fk_credito_cliente_1 FOREIGN KEY (historico_cli_id) references historico_cli_repres(id); 
ALTER TABLE credito_cliente ADD CONSTRAINT fk_credito_cliente_2 FOREIGN KEY (credito_cliente_cadastro_id) references credito_cliente_cadastro(id); 
ALTER TABLE grupo ADD CONSTRAINT fk_grupo_1 FOREIGN KEY (system_unit_id) references system_unit(id); 
ALTER TABLE historico_cli_repres ADD CONSTRAINT fk_historico_cli_repres_2 FOREIGN KEY (grupo_id) references ap_grupo_cliente(id); 
ALTER TABLE historico_cli_repres ADD CONSTRAINT fk_historico_cli_repres_3 FOREIGN KEY (repres_id) references ap_representante(id); 
ALTER TABLE historico_cli_repres ADD CONSTRAINT fk_historico_cli_repres_3 FOREIGN KEY (system_unit_id) references system_unit(id); 
ALTER TABLE historico_cli_repres ADD CONSTRAINT fk_historico_cli_repres_4 FOREIGN KEY (ap_cidade_id) references ap_cidade(id); 
ALTER TABLE historico_venda ADD CONSTRAINT fk_venda_6 FOREIGN KEY (system_unit_id) references system_unit(id); 
ALTER TABLE historico_venda ADD CONSTRAINT fk_venda_1 FOREIGN KEY (cidade_id) references ap_cidade(id); 
ALTER TABLE historico_venda ADD CONSTRAINT fk_venda_2 FOREIGN KEY (grupo_cliente_id) references ap_grupo_cliente(id); 
ALTER TABLE historico_venda ADD CONSTRAINT fk_venda_3 FOREIGN KEY (repres_id) references ap_representante(id); 
ALTER TABLE historico_venda ADD CONSTRAINT fk_historico_venda_5 FOREIGN KEY (meta_id) references meta(id); 
ALTER TABLE historico_venda ADD CONSTRAINT fk_historico_venda_6 FOREIGN KEY (estado_id) references ap_estado(id); 
ALTER TABLE historico_venda_item ADD CONSTRAINT fk_venda_item_1 FOREIGN KEY (venda_id) references historico_venda(id); 
ALTER TABLE historico_venda_item ADD CONSTRAINT fk_venda_item_2 FOREIGN KEY (grupo_estoque_id) references ap_grupo_estoque(id); 
ALTER TABLE historico_venda_item ADD CONSTRAINT fk_venda_item_3 FOREIGN KEY (subgrupo_estoque_id) references ap_subgrupo_estoque(id); 
ALTER TABLE historico_venda_item ADD CONSTRAINT fk_venda_item_4 FOREIGN KEY (familia_industrial_id) references ap_familia_industrial(id); 
ALTER TABLE historico_venda_item ADD CONSTRAINT fk_venda_item_5 FOREIGN KEY (familia_comercial_id) references ap_familia_comercial(id); 
ALTER TABLE log_crontab ADD CONSTRAINT fk_log_crontab_1 FOREIGN KEY (system_unit_id) references system_unit(id); 
ALTER TABLE meta ADD CONSTRAINT fk_meta_1 FOREIGN KEY (system_unit_id) references system_unit(id); 
ALTER TABLE meta_fechamento ADD CONSTRAINT fk_meta_fechamento_3 FOREIGN KEY (repres_id) references ap_representante(id); 
ALTER TABLE meta_fechamento ADD CONSTRAINT fk_meta_fechamento_1 FOREIGN KEY (meta_id) references meta(id); 
ALTER TABLE meta_fechamento ADD CONSTRAINT fk_meta_fechamento_2 FOREIGN KEY (meta_repres_id) references meta_repres(id); 
ALTER TABLE meta_feriado ADD CONSTRAINT fk_metas_feriados_1 FOREIGN KEY (meta_id) references meta(id); 
ALTER TABLE meta_import ADD CONSTRAINT fk_meta_import_1 FOREIGN KEY (ap_tabela_preco_id) references ap_tabela_preco(id); 
ALTER TABLE meta_import_fechamento ADD CONSTRAINT fk_meta_import_fechamento_1 FOREIGN KEY (meta_import_repres_id) references meta_import_repres(id); 
ALTER TABLE meta_import_fechamento ADD CONSTRAINT fk_meta_import_fechamento_2 FOREIGN KEY (meta_import_id) references meta_import(id); 
ALTER TABLE meta_import_fechamento ADD CONSTRAINT fk_meta_import_fechamento_3 FOREIGN KEY (ap_representante_id) references ap_representante(id); 
ALTER TABLE meta_import_item ADD CONSTRAINT fk_meta_import_item_1 FOREIGN KEY (meta_import_id) references meta_import(id); 
ALTER TABLE meta_import_repres ADD CONSTRAINT fk_metas_import_repres_1 FOREIGN KEY (ap_representante_id) references ap_representante(id); 
ALTER TABLE meta_import_repres ADD CONSTRAINT fk_metas_import_repres_2 FOREIGN KEY (meta_import_id) references meta_import(id); 
ALTER TABLE meta_import_tabela_preco ADD CONSTRAINT fk_meta_import_tabela_preco_1 FOREIGN KEY (ap_tabela_preco_id) references ap_tabela_preco(id); 
ALTER TABLE meta_import_tabela_preco ADD CONSTRAINT fk_meta_import_tabela_preco_2 FOREIGN KEY (meta_import_id) references meta_import(id); 
ALTER TABLE meta_repres ADD CONSTRAINT fk_meta_item_2 FOREIGN KEY (repres_id) references ap_representante(id); 
ALTER TABLE meta_repres ADD CONSTRAINT fk_metas_itens_1 FOREIGN KEY (meta_id) references meta(id); 
ALTER TABLE meta_trimestral_repres ADD CONSTRAINT fk_meta_trimestral_repres_1 FOREIGN KEY (meta_trimestral_id) references meta_trimestral(id); 
ALTER TABLE meta_trimestral_repres ADD CONSTRAINT fk_meta_trimestral_repres_2 FOREIGN KEY (ap_representante_id) references ap_representante(id); 
ALTER TABLE mini_meta ADD CONSTRAINT fk_mini_meta_2 FOREIGN KEY (mini_meta_tipo_id) references mini_meta_tipo(id); 
ALTER TABLE mini_meta ADD CONSTRAINT fk_mini_meta_3 FOREIGN KEY (system_unit_id) references system_unit(id); 
ALTER TABLE mini_meta ADD CONSTRAINT fk_mini_meta_3 FOREIGN KEY (ap_tabela_preco_id) references ap_tabela_preco(id); 
ALTER TABLE mini_meta_fechamento ADD CONSTRAINT fk_mini_meta_fechamento_1 FOREIGN KEY (mini_meta_id) references mini_meta(id); 
ALTER TABLE mini_meta_fechamento ADD CONSTRAINT fk_mini_meta_fechamento_2 FOREIGN KEY (ap_representante_id) references ap_representante(id); 
ALTER TABLE mini_meta_item ADD CONSTRAINT fk_mini_meta_item_1 FOREIGN KEY (mini_meta_id) references mini_meta(id); 
ALTER TABLE minimeta_tabela_preco ADD CONSTRAINT fk_minimeta_tabela_preco_1 FOREIGN KEY (ap_tabela_preco_id) references ap_tabela_preco(id); 
ALTER TABLE minimeta_tabela_preco ADD CONSTRAINT fk_minimeta_tabela_preco_2 FOREIGN KEY (mini_meta_id) references mini_meta(id); 
ALTER TABLE planejamento_import_dias ADD CONSTRAINT fk_planejamento_import_dias_1 FOREIGN KEY (planejamento_import_id) references planejamento_import(id); 
ALTER TABLE planejamento_import_excecao ADD CONSTRAINT planejamento_import_excecao_6a85b1cbb505a FOREIGN KEY (planejamento_import_id) references planejamento_import(id); 
ALTER TABLE preferencia_sistema ADD CONSTRAINT fk_preferencia_sistema_1 FOREIGN KEY (system_users_id) references system_users(id); 
ALTER TABLE premio ADD CONSTRAINT fk_premio_teste_1 FOREIGN KEY (tipo_premio_id) references tipo_premio(id); 
ALTER TABLE premio_regra ADD CONSTRAINT fk_regra_2 FOREIGN KEY (premio_id) references premio(id); 
ALTER TABLE premio_regra ADD CONSTRAINT fk_regra_1 FOREIGN KEY (comparador_id) references comparador(id); 
ALTER TABLE regra_prospeccao ADD CONSTRAINT fk_regra_prospeccao_1 FOREIGN KEY (system_unit_id) references system_unit(id); 
ALTER TABLE restricao_premio ADD CONSTRAINT fk_restricoes_persianas_1 FOREIGN KEY (premio_id) references premio(id); 
ALTER TABLE restricao_premio ADD CONSTRAINT fk_restricoes_persianas_2 FOREIGN KEY (ap_grupo_estoque_id) references ap_grupo_estoque(id); 
ALTER TABLE restricao_premio ADD CONSTRAINT fk_restricoes_persianas_3 FOREIGN KEY (ap_subgrupo_estoque_id) references ap_subgrupo_estoque(id); 
ALTER TABLE system_group_program ADD CONSTRAINT fk_system_group_program_2 FOREIGN KEY (system_group_id) references system_group(id); 
ALTER TABLE system_group_program ADD CONSTRAINT fk_system_group_program_1 FOREIGN KEY (system_program_id) references system_program(id); 
ALTER TABLE system_user_group ADD CONSTRAINT fk_system_user_group_1 FOREIGN KEY (system_group_id) references system_group(id); 
ALTER TABLE system_user_group ADD CONSTRAINT fk_system_user_group_2 FOREIGN KEY (system_user_id) references system_users(id); 
ALTER TABLE system_user_program ADD CONSTRAINT fk_system_user_program_1 FOREIGN KEY (system_program_id) references system_program(id); 
ALTER TABLE system_user_program ADD CONSTRAINT fk_system_user_program_2 FOREIGN KEY (system_user_id) references system_users(id); 
ALTER TABLE system_users ADD CONSTRAINT fk_system_user_1 FOREIGN KEY (system_unit_id) references system_unit(id); 
ALTER TABLE system_users ADD CONSTRAINT fk_system_user_2 FOREIGN KEY (frontpage_id) references system_program(id); 
ALTER TABLE system_user_unit ADD CONSTRAINT fk_system_user_unit_1 FOREIGN KEY (system_user_id) references system_users(id); 
ALTER TABLE system_user_unit ADD CONSTRAINT fk_system_user_unit_2 FOREIGN KEY (system_unit_id) references system_unit(id); 
ALTER TABLE trimestre_cliente_atual ADD CONSTRAINT fk_trimestre_cliente_atual_1 FOREIGN KEY (meta_trimestral_id) references meta_trimestral(id); 
ALTER TABLE trimestre_cliente_atual ADD CONSTRAINT fk_trimestre_cliente_atual_2 FOREIGN KEY (grupo_id) references ap_grupo_cliente(id); 
ALTER TABLE trimestre_cliente_atual ADD CONSTRAINT fk_trimestre_cliente_atual_3 FOREIGN KEY (repres_id) references ap_representante(id); 
ALTER TABLE trimestre_cliente_atual ADD CONSTRAINT fk_trimestre_cliente_atual_4 FOREIGN KEY (cidade_id) references ap_cidade(id); 
ALTER TABLE trimestre_cliente_atual ADD CONSTRAINT fk_trimestre_cliente_atual_5 FOREIGN KEY (estado_id) references ap_estado(id); 
ALTER TABLE trimestre_cliente_inicial ADD CONSTRAINT fk_trimestre_cliente_inicial_1 FOREIGN KEY (meta_trimestral_id) references meta_trimestral(id); 
ALTER TABLE trimestre_cliente_inicial ADD CONSTRAINT fk_trimestre_cliente_inicial_2 FOREIGN KEY (grupo_id) references ap_grupo_cliente(id); 
ALTER TABLE trimestre_cliente_inicial ADD CONSTRAINT fk_trimestre_cliente_inicial_3 FOREIGN KEY (repres_id) references ap_representante(id); 
ALTER TABLE trimestre_cliente_inicial ADD CONSTRAINT fk_trimestre_cliente_inicial_4 FOREIGN KEY (cidade_id) references ap_cidade(id); 
ALTER TABLE trimestre_cliente_inicial ADD CONSTRAINT fk_trimestre_cliente_inicial_5 FOREIGN KEY (estado_id) references ap_estado(id); 
