create schema trimestre_cliente; 

create schema trimestre_vendas; 

CREATE TABLE aptech_nota_fiscal( 
      id  INT IDENTITY    NOT NULL  , 
      nro_nfiscal char  (10)   , 
      dt_emissao datetime2   , 
      cod_clifor char  (7)   , 
      razao_clifor varchar  (255)   , 
      cod_cidade_clifor char  (5)   , 
      cod_grupo_clifor char  (8)   , 
      dt_change datetime2   , 
      cod_repres char  (7)   , 
      vendedor_interno char  (7)   , 
      vendedor_externo char  (7)   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE aptech_nota_fiscal_item( 
      id  INT IDENTITY    NOT NULL  , 
      aptech_nota_fiscal_id int   , 
      nro_nfiscal char  (10)   , 
      cod_item char  (10)   , 
      descricao varchar  (255)   , 
      quantidade float   , 
      valor_unitario float   , 
      perc_descto float   , 
      valor_descto float   , 
      valor_frete float   , 
      cod_grupoestoque char  (8)   , 
      cod_subgrupoestoque char  (8)   , 
      familia_comercial char  (8)   , 
      familia_industrial char  (8)   , 
      valor_total float   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE cidade( 
      cod_cidade  INT IDENTITY    NOT NULL  , 
      descricao nvarchar(max)   , 
      cep char  (10)   , 
      dipam_municipio char  (10)   , 
      zfm_municipio char  (10)   , 
      dfc_municipio char  (10)   , 
      cod_ibge varchar  (10)   , 
      dt_change datetime2   , 
      auxiliar_float1 float   , 
      auxiliar_float2 float   , 
      descricao_softwareemissor varchar  (60)   , 
      cod_siafi varchar  (20)   , 
      auxiliar_string1 varchar  (200)   , 
      auxiliar_string2 varchar  (200)   , 
      cod_anp varchar  (7)   , 
 PRIMARY KEY (cod_cidade)) ; 

CREATE TABLE clifor( 
      cod_clifor  INT IDENTITY    NOT NULL  , 
      razao varchar  (100)   NOT NULL  , 
      cod_situacaovenda char  (8)   , 
      cod_moeda char  (4)   , 
      cod_idioma char  (2)   , 
      cod_natrecdespfor char  (15)   , 
      cod_natrecdespcli char  (15)   , 
      cod_grpcliente char  (8)   , 
      cod_bairro char  (5)   NOT NULL  , 
      cod_grpfornec char  (4)   , 
      cod_redespacho char  (7)   , 
      cod_cidade char  (5)   NOT NULL  , 
      cod_transp char  (7)   , 
      cod_regiao char  (5)   NOT NULL  , 
      cod_repres char  (7)   , 
      cod_estado char  (2)   NOT NULL  , 
      fantasia varchar  (100)   NOT NULL  , 
      cod_pais char  (3)   NOT NULL  , 
      cod_condpagamento char  (20)   , 
      cod_portadorcr char  (20)   , 
      cod_portadorcp char  (20)   , 
      cod_atividade char  (20)   NOT NULL  , 
      endereco varchar  (100)   NOT NULL  , 
      cod_tabelapreco char  (20)   , 
      cod_tabelaprazo char  (10)   , 
      cod_natoperacaosai char  (20)   , 
      cod_natoperacaoent char  (20)   , 
      cliente char  (1)   NOT NULL  , 
      fornec char  (1)   NOT NULL  , 
      cep char  (10)   NOT NULL  , 
      pessoa char  (1)   NOT NULL  , 
      cgc_cpf char  (18)   NOT NULL  , 
      ie_rg varchar  (20)   , 
      insmunicipal varchar  (20)   , 
      telefone1 varchar  (20)   , 
      telefone2 varchar  (20)   , 
      celular varchar  (20)   , 
      fax varchar  (20)   , 
      cxpostal varchar  (15)   , 
      web varchar  (200)   , 
      email varchar  (200)   , 
      dt_cadastro datetime2   , 
      dt_atualizacao datetime2   , 
      dt_nascto datetime2   , 
      obs nvarchar(max)   , 
      suframa varchar  (20)   , 
      ativo char  (1)   NOT NULL  , 
      subst_tributaria_iss char  (1)   NOT NULL  , 
      aliquota_iss float   , 
      limite_credito float   , 
      dias_atraso int   , 
      dt_validadecredito datetime2   , 
      avaliacao_credito char  (1)   NOT NULL  , 
      cod_banco char  (3)   , 
      nro_agencia char  (7)   , 
      conta_corrente char  (15)   , 
      considerar_pedidocomp char  (1)   NOT NULL  , 
      motivo_bloqueio varchar  (200)   , 
      considerar_pedentfut char  (1)   NOT NULL  , 
      perc_descto float   , 
      agrupar_conhecimento char  (1)   NOT NULL  , 
      parametro_truck char  (1)   NOT NULL  , 
      cod_natopedentro char  (20)   , 
      cod_tabfrete char  (10)   , 
      parada_acertocontas char  (1)   , 
      cod_natopefora char  (20)   , 
      trk_conhecnfanf char  (1)   , 
      trk_tiporateio char  (1)   , 
      cod_endcobranca varchar  (20)   , 
      cod_endentrega varchar  (20)   , 
      exige_certificadoqualidade char  (1)   , 
      contato varchar  (60)   , 
      cgccpf_digito int   , 
      gera_manga char  (1)   , 
      tipo_descto char  (1)   , 
      pis_retidoclass char  (1)   , 
      cofins_retidoclass char  (1)   , 
      produtor_rural char  (1)   , 
      imp_boleto char  (1)   , 
      codigo_palm varchar  (50)   , 
      qld_qstrespondeu char  (1)   , 
      qld_qstdtenvio datetime2   , 
      qld_qstdtresposta datetime2   , 
      qld_qstresponsavel varchar  (60)   , 
      qld_iqf float   , 
      qld_dtiqf datetime2   , 
      comp_situacao char  (2)   , 
      comp_dtbloqueio datetime2   , 
      comp_motivo varchar  (200)   , 
      dt_validadeconsulta datetime2   , 
      ponto_referencia nvarchar(max)   , 
      cod_atividademunicipal nvarchar(max)   , 
      venda_situacao char  (2)   , 
      venda_dtbloqueio datetime2   , 
      venda_motivo varchar  (200)   , 
      dt_change datetime2   , 
      considerar_taxaboleto char  (1)   , 
      trk_tiposeguro varchar  (1)   , 
      auxiliar_string1 varchar  (200)   , 
      auxiliar_string2 varchar  (200)   , 
      numero int   , 
      end_complemento varchar  (100)   , 
      end_numero varchar  (10)   , 
      cod_motchegouempresa char  (8)   , 
      dt_motchegouempresa datetime2   , 
      cod_tipologradouro varchar  (15)   , 
      codigo_folhamatic varchar  (20)   , 
      tipo_controleboletoemail char  (1)   , 
      cod_itinerario varchar  (5)   , 
      cod_tipofrete char  (3)   , 
      perc_desctopv float   , 
      prazoaceite_validade int   , 
      iqf_notaquestionario float   , 
      iqf_indiceatendimento float   , 
      codigo_sisterceiro varchar  (20)   , 
      permite_alterartabprecopv char  (1)   , 
      aviso_faturamento nvarchar(max)   , 
      dt_validadeliberado datetime2   , 
      energia_telecomunicacao char  (1)   , 
      codtp_ccta varchar  (20)   , 
      codtp_tltu varchar  (20)   , 
      codtp_grupotensao varchar  (20)   , 
      energia_telecom char  (1)   , 
      prospect char  (1)   NOT NULL    DEFAULT 'N::bpchar NOT NULL', 
      auxiliar_float1 float   , 
      auxiliar_float2 float   , 
      perc_desctocr float   , 
      analise_gradetransp char  (1)   , 
      nfse_controle char  (1)   , 
      inscricao_produtorrural varchar  (20)   , 
      auxiliar_string3 varchar  (200)   , 
      auxiliar_string4 varchar  (200)   , 
      emitir_cartacobranca char  (1)   , 
      analisa_impostosretidosserv char  (1)   , 
      auxiliar_string5 varchar  (200)   , 
      ie_pessoafisica varchar  (20)   , 
      identificacao_estrangeiro varchar  (20)   , 
      identificacao_iedest char  (1)   , 
      auxiliar_string6 varchar  (200)   , 
      cod_tipopedvenda char  (5)   , 
      dt_valsuframa datetime2   , 
      tipo_crt char  (1)   , 
      hora_atualizacao char  (8)   , 
      exp_situacao char  (2)   , 
      exp_data datetime2   , 
      exp_hora char  (8)   , 
      imp_somentecxpostal char  (1)     DEFAULT 'N::bpchar', 
      agente_regularanp varchar  (10)   , 
      dispensado_coleta char  (1)   , 
      cod_formaspagto char  (2)   , 
      doc_ficticio char  (1)   NOT NULL    DEFAULT 'N::bpchar NOT NULL', 
 PRIMARY KEY (cod_clifor)) ; 

CREATE TABLE estado( 
      cod_estado  INT IDENTITY    NOT NULL  , 
      descricao varchar  (100)   NOT NULL  , 
      cod_mensagem char  (20)   , 
      icms_entrada float   , 
      icms_saida float   , 
      icms_interno float   , 
      aliq_icms_subst float   , 
      perc_icms_subst float   , 
      dt_change datetime2   , 
      trk_percseguro float   , 
      prazo_cancelamentonfe int   , 
      perc_fcp float  (16,6)   , 
      perc_fcpicmsop float  (16,6)   , 
      perc_anp float  (16,6)   , 
 PRIMARY KEY (cod_estado)) ; 

CREATE TABLE familia_comercial( 
      cod_fmcomercial  INT IDENTITY    NOT NULL  , 
      descricao varchar  (100)   NOT NULL  , 
      dt_change datetime2   , 
      permite_natconf varchar  (1)   , 
      tipo_detalhenfe char  (1)   , 
      codtp_grupofamilia varchar  (20)   , 
 PRIMARY KEY (cod_fmcomercial)) ; 

CREATE TABLE familia_industrial( 
      cod_fmindustrial  INT IDENTITY    NOT NULL  , 
      descricao varchar  (100)   , 
      dt_change datetime2   , 
 PRIMARY KEY (cod_fmindustrial)) ; 

CREATE TABLE grupo_cliente( 
      cod_grpcliente  INT IDENTITY    NOT NULL  , 
      cod_tabelaprazo char  (10)   , 
      cod_tabelapreco char  (20)   , 
      cod_portador char  (20)   , 
      cod_repres char  (7)   , 
      cod_condpagamento char  (20)   , 
      cod_transp char  (7)   , 
      descricao varchar  (100)   NOT NULL  , 
      perc_descto float   , 
      limite_credito float   , 
      inf_tabelaprazo char  (1)   NOT NULL  , 
      inf_tabelapreco char  (1)   NOT NULL  , 
      inf_portador char  (1)   NOT NULL  , 
      inf_repres char  (1)   NOT NULL  , 
      inf_condpagamento char  (1)   NOT NULL  , 
      inf_transp char  (1)   NOT NULL  , 
      inf_percdescto char  (1)   NOT NULL  , 
      inf_limitecredito char  (1)   NOT NULL  , 
      dt_change datetime2   , 
      considerar_taxaboleto char  (1)   , 
      inf_taxaboleto char  (1)   , 
      auxiliar_string1 varchar  (200)   , 
 PRIMARY KEY (cod_grpcliente)) ; 

CREATE TABLE grupo_estoque( 
      cod_grupoestoque  INT IDENTITY    NOT NULL  , 
      descricao varchar  (100)   NOT NULL  , 
      qtd_niveil int   , 
      item_venda char  (1)   NOT NULL  , 
      item_producao char  (1)   NOT NULL  , 
      item_compraprodutivo char  (1)   NOT NULL  , 
      item_compranaoprodutivo char  (1)   NOT NULL  , 
      margem_lucro float   , 
      seq_exibicao int   , 
      dt_change datetime2   , 
      codigo_sisterceiro varchar  (20)   , 
      exibir_itemfilhograde char  (1)   , 
      tipo_detalhenfe char  (1)   , 
      auxiliar_string1 varchar  (200)   , 
      auxiliar_string2 varchar  (200)   , 
      codtp_tipoproduto varchar  (20)   , 
      exibiritens_coltransfpro char  (1)   , 
      sigla_codautomatico varchar  (10)   , 
      cod_tipoos char  (2)   , 
      auxiliar_float1 float  (16,6)   , 
      dispensado_coleta char  (1)   , 
      perc_descto float     DEFAULT 0, 
 PRIMARY KEY (cod_grupoestoque)) ; 

CREATE TABLE item( 
      cod_item  INT IDENTITY    NOT NULL  , 
      cod_clifor char  (7)   , 
      cod_servicorf char  (10)   , 
      cod_subgrupoestoque char  (8)   , 
      cod_moeda char  (4)   , 
      cod_grade char  (10)   , 
      cod_tributacao char  (4)   NOT NULL  , 
      cod_grupoestoque char  (8)   NOT NULL  , 
      cod_fmcomercial char  (8)   NOT NULL  , 
      cod_unidade char  (6)   , 
      cod_fmindustrial char  (8)   , 
      cod_unidade2 char  (6)   , 
      cod_unidadecompra char  (6)   , 
      cod_unidadevenda char  (6)   , 
      fornec_default char  (7)     DEFAULT character(7) COLLATE pg_catalog.default, 
      codigo char  (20)   NOT NULL  , 
      cod_tabelaprazo char  (10)   , 
      descricao varchar  (100)   NOT NULL  , 
      preco_reposicao float   , 
      desc_nfiscal varchar  (100)   , 
      desc_cupom varchar  (60)   , 
      unidade_cupom char  (6)   , 
      narrativa nvarchar(max)   , 
      peso_bruto float   , 
      custo_reposicao float   , 
      peso_liquido float   , 
      preco_venda float   , 
      custo_medio float  (16,6)   , 
      dt_altprecovenda datetime2   , 
      ativo char  (1)   NOT NULL  , 
      preco_promocao float   , 
      custo_standard float   , 
      dt_inclusao datetime2   NOT NULL  , 
      qtd_seguranca float   , 
      dt_atualizacao datetime2   , 
      controla_lote char  (1)   NOT NULL  , 
      dt_ultimacontagem datetime2   , 
      qtd_lotemincompra float   , 
      qtd_maxima float   , 
      controla_estoque char  (1)   NOT NULL  , 
      qtd_loteminproducao float   , 
      comprado_fabricado char  (1)   NOT NULL  , 
      item_debitodireto char  (1)   NOT NULL  , 
      lt_multiplo_compra char  (1)   NOT NULL  , 
      cod_classfiscal char  (20)   , 
      lt_multiplo_producao char  (1)   NOT NULL  , 
      tipo_produto char  (1)   NOT NULL  , 
      controlado char  (1)   NOT NULL  , 
      composto char  (1)   NOT NULL  , 
      motivo_bloqueio varchar  (200)   , 
      aceita_desconto char  (1)   NOT NULL  , 
      path_foto varchar  (200)   , 
      descto_maximo float   , 
      marg_lucroideal float   , 
      dt_iniciopromocao datetime2   , 
      dt_terminopromocao datetime2   , 
      promocao_atualizademanda char  (1)   NOT NULL  , 
      dt_bloqueio datetime2   , 
      prender_cqrecebimento char  (1)   NOT NULL  , 
      prender_cqproducao char  (1)   NOT NULL  , 
      tmp_preco_venda float   , 
      tmp_preco_promocao float   , 
      tmp_dt_iniciopromocao datetime2   , 
      tmp_dt_terminopromocao datetime2   , 
      tmp_aceita_desconto char  (1)   , 
      tmp_descto_maximo float   , 
      tmp_promocao_atualizademanda char  (1)   , 
      tmp_alterado char  (1)   , 
      tmp_codtabelaprazo char  (10)   , 
      altura float   , 
      largura float   , 
      dimensao char  (20)   , 
      comprimento float   , 
      volume_m3 float   , 
      gramatura float   , 
      qtd_folhas int   , 
      formato char  (10)   , 
      concentracao float   , 
      aplicacao varchar  (200)   , 
      nro_ultimapeca int   , 
      perc_distribuicao float   , 
      perc_perdas float   , 
      perc_adm float   , 
      perc_vendas float   , 
      versao_operacao char  (10)   , 
      dt_ultcotacao datetime2   , 
      preco_ultcotacao float   , 
      tipo_custo int   , 
      fornec_ultcotacao varchar  (60)   , 
      imprimir_narrativapc char  (1)   , 
      imprimir_narrativapv char  (1)   , 
      imprimir_narrativarom char  (1)   , 
      custo_calculado float   , 
      imprimir_narrativaop char  (1)   , 
      preco_vendasugerido float   , 
      tempo_obtencaoideal int   , 
      tipo_controlelote char  (1)   NOT NULL  , 
      controla_validade char  (1)   NOT NULL  , 
      prazo_validade float   , 
      tipo_controlepeca char  (1)   NOT NULL  , 
      curva_abc char  (2)   , 
      saldo_negativo char  (1)   NOT NULL  , 
      fator_quantidade2 float   , 
      desenho varchar  (30)   , 
      rev_desenho varchar  (15)   , 
      dt_revdesenho datetime2   , 
      dnf_fator_01 float   , 
      dnf_fator_02 float   , 
      dnf_fator_03 float   , 
      dnf_codespecie varchar  (10)   , 
      dnf_codproduto1 varchar  (10)   , 
      dnf_codproduto2 varchar  (10)   , 
      dnf_un_padrao char  (2)   , 
      dnf_un_est1 char  (2)   , 
      dnf_un_est2 char  (2)   , 
      dnf_capacidade int   , 
      dnf_comb_solvente char  (1)   , 
      dnf_sefaz char  (4)   , 
      dnf_codgrupo varchar  (20)   , 
      gera_manga char  (1)   , 
      prazo_entrega int   , 
      auxiliar_string1 varchar  (200)   , 
      auxiliar_string2 varchar  (200)   , 
      imprimir_narrativanf char  (1)   , 
      sittributaria char  (3)   , 
      auxiliar_float1 float   , 
      auxiliar_float2 float   , 
      dt_change datetime2   , 
      tipo_aliqipi char  (1)   , 
      valor_ipifixo float   , 
      tipo_tempoobtencaocom char  (1)   , 
      tipo_tempoobtencaopro char  (1)   , 
      tempo_obtencaoidealpro float   , 
      sanfona float   , 
      face float   , 
      narrativa_op nvarchar(max)   , 
      modelo varchar  (200)   , 
      calcular_volumeauto char  (1)   , 
      codtp_anp varchar  (20)   , 
      codtp_sefaz varchar  (20)   , 
      codtp_servicolc varchar  (20)   , 
      codtp_genero varchar  (20)   , 
      garantia_adicional float   , 
      garantia float   , 
      qtd_segurancadias float   , 
      codtp_packing varchar  (20)   , 
      descricao_completa varchar  (200)   , 
      codtp_energiatelecom_cf varchar  (20)   , 
      descricao_web nvarchar(max)   , 
      link_video varchar  (200)   , 
      qtd_embalagem float   , 
      diametro varchar  (20)   , 
      auxiliar_string3 varchar  (200)   , 
      confrecfisico_integrabalanca char  (1)   , 
      qtdetotal_coltransfpro char  (1)   , 
      codtp_tipoinventario varchar  (20)   , 
      fiscal_contaanalitica varchar  (50)   , 
      ctr_itemdespesa char  (1)   , 
      ctr_itemservtipo char  (1)   , 
      permite_vinculoagenda char  (1)   , 
      perc_tribaproxnac float   , 
      perc_tribaproximp float   , 
      historico_tribaprox nvarchar(max)   , 
      codtp_codigotabela02 varchar  (20)   , 
      codtp_codigotabela01 varchar  (20)   , 
      codigo_sequencia int   , 
      auxiliar_string4 varchar  (200)   , 
      md5_bloco7 varchar  (32)   , 
      perc_tribaproxuf float  (16,6)   , 
      perc_tribaproxmun float  (16,6)   , 
      fonte_leitransparencia varchar  (34)   , 
      chave_leitransparencia char  (6)   , 
      limite_minimo float  (16,6)   , 
      limite_maximo float  (16,6)   , 
      ind_escalarelevante char  (1)   , 
      prodanvisa varchar  (13)   , 
      hora_atualizacao char  (8)   , 
      exp_situacao char  (2)   , 
      exp_data datetime2   , 
      exp_hora char  (8)   , 
      numreg_anp char  (40)   , 
      arf_medlista char  (1)   , 
      arf_medtipo char  (1)   , 
      sincronizar_ecommerce char  (1)   , 
      xmotivoisencao varchar  (255)   , 
      nro_loterastreio varchar  (20)   , 
      dt_fabricacaorastreio datetime2   , 
      dt_validaderastreio datetime2   , 
      integracao_pontuacao char  (1)     DEFAULT 'N::bpchar', 
      mercafacil_sincronizado char  (1)   , 
      mercafacil_dtultimasinc datetime2   , 
      origem_merc char  (1)   , 
 PRIMARY KEY (cod_item)) ; 

CREATE TABLE pedido_venda( 
      id  INT IDENTITY    NOT NULL  , 
      cod_pedidovenda char  (10)   NOT NULL  , 
      cod_clifor char  (7)   NOT NULL  , 
      cod_portador2 char  (20)   , 
      cod_tipopedvenda char  (5)   , 
      cod_gerente char  (10)   , 
      cod_portador char  (20)   , 
      cod_orcamentista char  (10)   , 
      cod_empresa char  (3)   NOT NULL  , 
      cod_prioridade char  (8)   , 
      cod_tabelapreco char  (20)   , 
      cod_repres char  (7)   , 
      cod_transp char  (7)   NOT NULL  , 
      cod_condpagamento char  (20)   NOT NULL  , 
      cod_moeda char  (4)   NOT NULL  , 
      contato varchar  (60)   , 
      cod_endcobranca char  (20)   , 
      cod_usuario char  (10)   , 
      cod_condpagamento2 char  (20)   , 
      redespacho char  (7)   , 
      nro_pedcliente varchar  (30)   , 
      dt_emissao datetime2   NOT NULL  , 
      dt_solicitada_apos datetime2   , 
      dt_solicitada_limite datetime2   , 
      situacao char  (1)   NOT NULL  , 
      dt_validade datetime2   , 
      pedido_orcamento char  (1)   NOT NULL  , 
      aceita_ftparcial char  (1)   NOT NULL  , 
      dt_previsaofechamento datetime2   , 
      tipo_frete char  (1)   NOT NULL  , 
      val_frete float   , 
      val_seguro float   , 
      dt_aprovacao datetime2   , 
      quem_aprovou varchar  (60)   , 
      valor_despesas float   , 
      cod_endentrega char  (20)   , 
      mensagem nvarchar(max)   , 
      mensagem_nf nvarchar(max)   , 
      tipo_mensagemnf char  (1)   NOT NULL  , 
      inf_comissao char  (1)   NOT NULL  , 
      paga_comissao char  (1)   NOT NULL  , 
      liberado char  (1)   , 
      perc_comissaofatura float   , 
      dt_cancelou datetime2   , 
      perc_comissaorecebe float   , 
      usuario_cancelou char  (10)   , 
      cod_motcancelamento char  (8)   , 
      motivo_cancelou varchar  (200)   , 
      perc_descto float   , 
      impresso char  (1)   , 
      tipo_descto char  (1)   NOT NULL  , 
      pros_nome varchar  (60)   , 
      pros_contato varchar  (60)   , 
      pros_telefone varchar  (20)   , 
      pros_celular varchar  (20)   , 
      pros_uf char  (2)   , 
      pros_email varchar  (200)   , 
      pros_obs nvarchar(max)   , 
      tipo_taxamoeda char  (1)   NOT NULL  , 
      valor_taxamoeda float   , 
      referencia varchar  (200)   , 
      arq_descproposta varchar  (200)   , 
      arq_condgeral varchar  (200)   , 
      valor_bcalc_repasseicms float   , 
      valor_repasseicms float   , 
      valor_bcalc_zonafranca float   , 
      valor_zonafranca float   , 
      valor_bcalc_iss float   , 
      valor_iss float   , 
      exp_situacao char  (2)   , 
      exp_data datetime2   , 
      exp_hora char  (5)   , 
      dt_inclusao datetime2   , 
      dt_alteracao datetime2   , 
      cliente_geramanga char  (1)   , 
      imp_boleto char  (1)   , 
      codigo_palm varchar  (20)   , 
      sep_status char  (2)   , 
      sep_usuario char  (10)   , 
      sep_dtinicio datetime2   , 
      sep_hsinicio char  (5)   , 
      cod_orcamento char  (10)   , 
      obs_proposta nvarchar(max)   , 
      prazo_entrega varchar  (200)   , 
      dt_proximocontato datetime2   , 
      anotacao_followup nvarchar(max)   , 
      dt_envio datetime2   , 
      dt_change datetime2   , 
      status_web varchar  (1)   , 
      origem varchar  (1)   , 
      dt_finalizadoweb datetime2   , 
      dt_baixadoweb datetime2   , 
      recalculo_web char  (1)   , 
      perc_comissaopedido float   , 
      auxiliar_string1 varchar  (200)   , 
      auxiliar_string2 varchar  (200)   , 
      cod_tipofrete char  (3)   NOT NULL    DEFAULT '001::bpchar NOT NULL', 
      cod_taxasucesso char  (8)   , 
      cod_ordemseparacao int   , 
      nro_pedidovendaint varchar  (30)   , 
      email_boleto char  (1)   , 
      dt_concluiudigitacao datetime2   , 
      cod_ficha int   , 
      valor_fretepeso float   , 
      em_analise char  (1)   , 
      cod_usuarioanalise char  (10)   , 
      cod_cliforoptring char  (7)   , 
      pjt_codempresa char  (3)   , 
      pjt_codprojeto varchar  (20)   , 
      dt_solicitacao datetime2   , 
      dt_gerandodav datetime2   , 
      qtd_caixas char  (15)   , 
      especie_emb varchar  (20)   , 
      peso_bruto float   , 
      peso_liquido float   , 
      cod_empresapvenda char  (3)   , 
      cod_pontovendapvenda int   , 
      dt_pvenda datetime2   , 
      hr_pvenda char  (8)   , 
      nome_ficha varchar  (100)   , 
      cod_formaspagto char  (2)   , 
      nro_pedidovendaint2 varchar  (30)   , 
      liberado_old char  (2)   , 
      exec_libbloq char  (1)   , 
      obs_libbloq nvarchar(max)   , 
      tipo_ecommerce char  (2)   , 
      usuario_alteracao char  (10)   , 
      tipo_integracao varchar  (100)   , 
      id_transporteint varchar  (50)   , 
      recalc_dup char  (1)   , 
      recalc_pagto char  (1)   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE pedvenda_item( 
      id  INT IDENTITY    NOT NULL  , 
      cod_pedidovenda char  (10)   NOT NULL  , 
      cod_empresa char  (3)   NOT NULL  , 
      cod_etapa char  (8)   , 
      cod_taxasucesso char  (8)   , 
      cod_prioridade char  (8)   , 
      cod_motcancelamento char  (8)   , 
      os_empresa char  (3)   , 
      os_ordemservico char  (10)   , 
      sequencia int   NOT NULL  , 
      cod_pedidocompra char  (10)   , 
      os_sequencia int   , 
      cod_tabelapreco char  (20)   , 
      seq_pedcompra int   , 
      cod_serie char  (10)   , 
      cod_natoperacao char  (20)   NOT NULL  , 
      cod_item char  (10)   NOT NULL  , 
      qtd_pedida float   NOT NULL  , 
      qtd_atendida float   , 
      preco_vendatabela float   , 
      qtd_liberada float   , 
      preco_venda float   , 
      aliq_icms float   , 
      preco_reposicao float   , 
      aliq_ipi float   , 
      custo_reposicao float   , 
      custo_medio float   , 
      custo_standard float   , 
      valor_descto float   , 
      perc_base_icms float   , 
      perc_descto float   , 
      aliq_iss float   , 
      situacao_item char  (1)   NOT NULL  , 
      dt_inclusao datetime2   NOT NULL  , 
      dt_cancelado datetime2   , 
      base_icms float   , 
      usuario_cancelou char  (10)   , 
      base_icms_sub float   , 
      motivo_cancelou varchar  (200)   , 
      valor_total float   , 
      dt_solicitada datetime2   NOT NULL  , 
      valor_icms float   , 
      dt_suspenso datetime2   , 
      valor_icms_sub float   , 
      dt_atendida datetime2   , 
      valor_ipi float   , 
      usuario_suspendeu char  (10)   , 
      valor_iss float   , 
      motivo_suspendeu varchar  (200)   , 
      usar_flag_fat char  (1)   NOT NULL  , 
      obs nvarchar(max)   , 
      item_descricao varchar  (100)   , 
      periodo_consumo varchar  (20)   , 
      referencia varchar  (20)   , 
      desenho varchar  (30)   , 
      amostra varchar  (30)   , 
      dt_prazoentcot datetime2   , 
      desenv_codigo varchar  (20)   , 
      desenv_descricao varchar  (100)   , 
      desenv_unidade char  (6)   , 
      desenv_periodo varchar  (15)   , 
      lote_minimo float   , 
      diametro_coluna float   , 
      valor_bcalc_repasseicms float   , 
      perc_repasseicms float   , 
      valor_repasseicms float   , 
      valor_bcalc_zonafranca float   , 
      desc_zonafranca float   , 
      valor_zonafranca float   , 
      valor_bcalc_iss float   , 
      iss_perc_reducao float   , 
      aprec_custoreposicao float   , 
      valor_ferramental float   , 
      valor_bcalc_pis float   , 
      valor_bcalc_cofins float   , 
      valor_pis float   , 
      valor_cofins float   , 
      aliq_pis float   , 
      aliq_cofins float   , 
      pis_codtributacao char  (1)   , 
      cofins_codtributacao char  (1)   , 
      cod_usuario char  (10)   , 
      dt_alteracao datetime2   , 
      item_geramanga char  (1)   , 
      percentual_manga float   , 
      cod_unidadevenda char  (6)   , 
      fator_conversao float   , 
      qtd_venda float   , 
      preco_unitvenda float   , 
      opcional char  (1)   , 
      preco_vdacomimpostoipi float   , 
      preco_vdatabelacomipi float   , 
      preco_unitvdacomipi float   , 
      tipo_descto char  (1)   , 
      taxa_tabelaprazo float   , 
      seq_relnecessidade int   , 
      set_relnecessidade char  (1)   , 
      dt_change datetime2   , 
      perc_confnat1 float   , 
      perc_confnat2 float   , 
      auxiliar_string1 varchar  (200)   , 
      auxiliar_string2 varchar  (200)   , 
      obs_itemnf nvarchar(max)   , 
      auxiliar_float1 float   , 
      auxiliar_float2 float   , 
      nro_pedidovendaint varchar  (30)   , 
      preco_vendatabela2 float   , 
      pvi_tipoprecosugerir char  (1)   , 
      cod_ambiente char  (5)   , 
      cod_sugestao int   , 
      descricao_sugestao varchar  (100)   , 
      ambiente_apelido varchar  (40)   , 
      qtd_projeto float   , 
      percentual_perda float   , 
      tipo_percentualperda char  (1)   , 
      tipo_sugestaoambiente char  (1)   , 
      comprimento float   , 
      largura float   , 
      cod_tipopedvenda char  (5)   , 
      osp_codempresa char  (3)   , 
      osp_codordemservico char  (10)   , 
      osp_sequencia int   , 
      origem char  (2)   , 
      osl_codempresa char  (3)   , 
      osl_codordemservico char  (10)   , 
      osl_sequencia int   , 
      seq_nropedcliente int   , 
      ctr_itemservtipo char  (1)   , 
      perc_base_icmsst float   , 
      pvi_dtentregaplanejada datetime2   , 
      subtrai_icmsdeson char  (1)     DEFAULT 'N::bpchar', 
      motivo_desonicms int   , 
      valor_desonicms float   , 
      aliq_desonicms float   , 
      seq_exibicao int   , 
      valor_fcpst float   , 
      preco_vendaoriginal float   , 
      cod_natoperfatef char  (20)   , 
      auxiliar_string3 nvarchar(max)   , 
      sequencia_pai int   , 
      nro_pedcliente varchar  (20)   , 
      cod_cenario int   , 
      sequencia_cenario int   , 
      imp_pedprogramado char  (1)   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE repres_comissao( 
      cod_represcomissao  INT IDENTITY    NOT NULL  , 
      cod_repres char  (7)   NOT NULL  , 
      cod_empresa char  (3)   NOT NULL  , 
      cod_clifor char  (7)   NOT NULL  , 
      cod_item char  (10)   NOT NULL  , 
      perc_comissao float   NOT NULL  , 
      cod_grupoestoque char  (8)   NOT NULL  , 
      cod_condpagamento char  (20)   NOT NULL  , 
      desconto_inicial float   NOT NULL  , 
      participacao char  (1)   NOT NULL  , 
      limite_partic float   , 
      desconto_final float   NOT NULL  , 
      perc_partic float   , 
      dt_change datetime2   , 
      cod_estado varchar  (2)   NOT NULL    DEFAULT '*::varchar', 
      cod_regiao varchar  (5)   NOT NULL    DEFAULT '*::varchar', 
      cod_grpcliente char  (8)   NOT NULL    DEFAULT '*::varchar', 
      cod_tipofrete char  (3)   NOT NULL    DEFAULT '001::bpchar', 
      tipo_descto char  (1)   , 
      tipo_perccomissao char  (1)   , 
      comissao_objetivo float   , 
      indice_mes float   , 
      prazo_mediopadrao float   , 
      cod_fmcomercial char  (8)   NOT NULL    DEFAULT '*::bpchar', 
      cod_fabricante char  (7)   NOT NULL    DEFAULT '*::bpchar', 
      cod_subgrupoestoque char  (8)   , 
 PRIMARY KEY (cod_represcomissao)) ; 

CREATE TABLE representante( 
      cod_repres  INT IDENTITY    NOT NULL  , 
      razao varchar  (100)   NOT NULL  , 
      cod_bairro char  (5)   NOT NULL  , 
      cod_cidade char  (5)   NOT NULL  , 
      cod_regiao char  (5)   NOT NULL  , 
      cod_banco char  (3)   , 
      cod_pais char  (3)   NOT NULL  , 
      fantasia varchar  (100)   NOT NULL  , 
      cod_estado char  (2)   NOT NULL  , 
      endereco varchar  (100)   NOT NULL  , 
      cep char  (10)   NOT NULL  , 
      pessoa char  (1)   NOT NULL  , 
      cgc_cpf char  (18)   NOT NULL  , 
      ie_rg varchar  (20)   , 
      telefone1 varchar  (20)   , 
      insmunicipal varchar  (20)   , 
      telefone2 varchar  (20)   , 
      fax varchar  (20)   , 
      celular varchar  (20)   , 
      cxpostal char  (15)   , 
      web varchar  (200)   , 
      email varchar  (200)   , 
      dt_cadastro datetime2   , 
      dt_atualizacao datetime2   , 
      contato varchar  (60)   , 
      obs nvarchar(max)   , 
      nro_depend int   , 
      cod_contabilcr char  (30)   , 
      cod_contabildb char  (30)   , 
      agencia char  (7)   , 
      nro_conta char  (15)   , 
      comissao_padrao float   , 
      ativo char  (1)   NOT NULL  , 
      imp_rendafonte char  (1)   NOT NULL  , 
      motivo_bloqueio varchar  (200)   , 
      pode_desconto char  (1)   NOT NULL  , 
      descto_maximo float   , 
      comissao_tipobase char  (1)   NOT NULL  , 
      calcular_icms char  (1)   NOT NULL  , 
      calcular_ipi char  (1)   NOT NULL  , 
      calcular_pis char  (1)   NOT NULL  , 
      calcular_cofins char  (1)   NOT NULL  , 
      calcular_juros char  (1)   NOT NULL  , 
      calcular_descto char  (1)   NOT NULL  , 
      paga_comissao char  (1)   NOT NULL  , 
      perc_comissaofatura float   NOT NULL  , 
      perc_comissaorecebe float   NOT NULL  , 
      email_pedven char  (1)   NOT NULL  , 
      email_emisnf char  (1)   NOT NULL  , 
      percentual_manga float   , 
      dt_change datetime2   , 
      auxiliar_string1 varchar  (200)   , 
      auxiliar_string2 varchar  (200)   , 
      gerar_titulocomissaocp varchar  (1)   , 
      perc_comissaopedido float   , 
      auxiliar_float1 float   , 
      auxiliar_float2 float   , 
      calcular_icmssub char  (1)   , 
      calcular_icmsst char  (1)   , 
 PRIMARY KEY (cod_repres)) ; 

CREATE TABLE subgrupo_estoque( 
      cod_grupoestoque char  (8)   NOT NULL  , 
      cod_subgrupoestoque  INT IDENTITY    NOT NULL  , 
      descricao varchar  (100)   NOT NULL  , 
      ativo char  (1)   NOT NULL  , 
      dt_inclusao datetime2   NOT NULL  , 
      dt_atualizacao datetime2   NOT NULL  , 
      dt_bloqueio datetime2   , 
      motivo_bloqueio varchar  (200)   , 
      seq_exibicao int   , 
      dt_change datetime2   , 
 PRIMARY KEY (cod_subgrupoestoque)) ; 

CREATE TABLE tapecaria_grupo( 
      cod_grupoestoque  INT IDENTITY    NOT NULL  , 
      descricao varchar  (100)   NOT NULL  , 
 PRIMARY KEY (cod_grupoestoque)) ; 

 
  
 ALTER TABLE aptech_nota_fiscal_item ADD CONSTRAINT fk_aptech_nota_fiscal_item_1 FOREIGN KEY (aptech_nota_fiscal_id) references aptech_nota_fiscal(id); 
ALTER TABLE subgrupo_estoque ADD CONSTRAINT fk_subgrupo_estoque_1 FOREIGN KEY (cod_grupoestoque) references grupo_estoque(cod_grupoestoque); 

 CREATE VIEW trimestre_cliente.trimestre_cliente AS select 	y.consultor as "representante", 
		y.cod_repres as "cod_repres",
		y.repres_email as "repres_email",
		y.grupo_empresarial as "grupo_empresarial", 
		y.principal as "cod_principal", 
	    (select c.razao from clifor as c where c.cod_clifor = y.principal) as "razao_principal", 
		y.codigo as "cod_clifor", 
		y.razao as "razao_social", 
		y.grupo_cliente as "grupo_cliente", 
		y.dt_cadastro as "dt_cadastro", 
		y.ativo as "ativo"
from (
select  x.consultor , x.repres_email , x.cod_repres , x.grupo_empresarial ,
		(case when (x.Grupo_Empresarial = 'Sim') then
		   (case when x.ativo = 'S' then 
		   		(case when (x.cod_clifor > (select f.cod_filial from 	clifor_filial as f , clifor as c 
			 								where 	c.cod_clifor = f.cod_filial and f.cod_clifor = x.cod_clifor and c.ativo = 'S' and c.cod_grpcliente <> 'TR' 
			 								order by f.cod_filial limit 1) ) then 
						(select f.cod_filial from 	clifor_filial as f , clifor as c 
			 	 		where 	c.cod_clifor = f.cod_filial and f.cod_clifor = x.cod_clifor and c.ativo = 'S' and c.cod_grpcliente <> 'TR'
			 	 		order by f.cod_filial limit 1)											 
			     else
    	            x.cod_clifor
				 end)
			else
				(case when (select f.cod_filial from clifor_filial as f , clifor as c 
	 	 		 where 	c.cod_clifor = f.cod_filial and f.cod_clifor = x.cod_clifor and c.ativo = 'S' and c.cod_grpcliente <> 'TR'
 	 	 		 order by f.cod_filial limit 1) is not null then 
						(select f.cod_filial from 	clifor_filial as f , clifor as c 
	 	 		 		where 	c.cod_clifor = f.cod_filial and f.cod_clifor = x.cod_clifor and c.ativo = 'S' and c.cod_grpcliente <> 'TR'
 	 	 		 		order by f.cod_filial limit 1)
				 else
				   		(case when (x.cod_clifor > (select f.cod_filial from 	clifor_filial as f , clifor as c 
					 								where 	c.cod_clifor = f.cod_filial and f.cod_clifor = x.cod_clifor and c.ativo = 'N' and c.cod_grpcliente <> 'TR'
			 										order by f.cod_filial limit 1) ) then 
								(select f.cod_filial from 	clifor_filial as f , clifor as c 
					 	 		where 	c.cod_clifor = f.cod_filial and f.cod_clifor = x.cod_clifor and c.ativo = 'N' and c.cod_grpcliente <> 'TR'
			 			 		order by f.cod_filial limit 1)											 
			     		else
    	            		x.cod_clifor
				 		end)
				 end)
			end)
		 else
		    x.cod_clifor
	     end) as Principal , 
		
		 x.cod_clifor as codigo ,  x.razao , x.grupo_cliente , x.dt_cadastro , 
  
		(case when (x.Grupo_Empresarial = 'Sim') then
		   (case when x.ativo = 'S' then 
				x.ativo			
			else
				(case when (select f.cod_filial from 	clifor_filial as f , clifor as c 
	 	 		 where 	c.cod_clifor = f.cod_filial and f.cod_clifor = x.cod_clifor and c.ativo = 'S' and c.cod_grpcliente <> 'TR'
 	 	 		 order by f.cod_filial limit 1) is not null then 
						(select c.ativo from 	clifor_filial as f , clifor as c 
	 	 		 		where 	c.cod_clifor = f.cod_filial and f.cod_clifor = x.cod_clifor and c.ativo = 'S' and c.cod_grpcliente <> 'TR'
 	 	 		 		order by f.cod_filial limit 1)
				 else
				        x.ativo
				 end)
			end)
		 else
		    x.ativo
	     end) as Ativo  
  
from (
		select 		c.cod_clifor , c.razao , g.descricao as Grupo_Cliente , c.dt_cadastro , c.ativo , r.fantasia as consultor , r.email as repres_email , r.cod_repres ,
					(case when 
					 (select f.cod_clifor from clifor_filial as f where f.cod_clifor = c.cod_clifor group by f.cod_clifor) is not null then
						      'Sim'
					  else
						      'Não'
					  end) as Grupo_Empresarial
		from 		clifor as c , grupo_cliente as g , representante as r
		where 	c.cod_grpcliente is not null and c.cod_grpcliente = g.cod_grpcliente and g.descricao not in ('ORÇAMENTO (COMERCIAL)','NÃO APLICÁVEL','COLABORADOR','BLOQUEADO - NÃO PODE REATIVAR')
				and r.cod_repres = c.cod_repres and r.ativo = 'S'
) as x
) as y
order by y.consultor ,y.grupo_empresarial , y.principal



; 

CREATE VIEW trimestre_vendas.trimestre_vendas AS select 
  (TAB.DATA_DE_EMISSAO) as "data_emissao", 
  (TAB.DATA_CADASTRO) as "clifor_data_cadastro", 
  trim(TAB.NRO_NOTA_FISCAL) as "nro_nf", 
  trim(TAB.CODIGO_CLIENTE) as "cod_clifor", 
  trim(TAB.RAZAO_SOCIAL) as "clifor_razao", 
  trim(TAB.AGENTE_REGULARANP) as "clifor_agente", 
  trim(TAB.MUNICIPIO) as "clifor_cidade", 
  trim(TAB.Estado) as "clifor_estado", 
  trim(TAB.UF) as "clifor_uf", 
  trim(TAB.GRUPO_CLIENTE) as "clifor_grp", 
  trim(TAB.CODIGO_ITEM) as "cod_item", 
  trim(TAB.DESCRICAO_ITEM) as "item_descricao", 
  trim(TAB.COD_REPRES) as "cod_repres", 
  (TAB.SEQUENCIA) as "seq_item", 
  trim(TAB.RAZAO_REPRES) as "repres_razao", 
  trim(TAB.FANTASIA_REPRES) as "repres_fantasia", 
  trim(TAB.EMAIL_REPRES) as "repres_email", 
  (TAB.QTDE) as "item_quantidade", 
  sum(TAB.VALOR_TOTAL) as "item_valor_total", 
  SUM(CASE WHEN TAB.SEQUENCIA = 12 THEN TAB.VALOR_TOTAL ELSE 0 END) AS "item_valor_mostruario" 
FROM 
  (
    select 
      nota_fiscal.dt_emissao as DATA_DE_EMISSAO, 
      clifor.dt_cadastro as DATA_CADASTRO, 
      nota_fiscal.nro_nfiscal as NRO_NOTA_FISCAL, 
      nota_fiscal.cod_clifor as CODIGO_CLIENTE, 
      clifor.razao as RAZAO_SOCIAL, 
      clifor.agente_regularanp as AGENTE_REGULARANP, 
      cidade.descricao as MUNICIPIO, 
      estado.descricao as ESTADO, 
      clifor.cod_estado as UF, 
      grupo_cliente.descricao as GRUPO_CLIENTE, 
      item.codigo AS CODIGO_ITEM, 
      item.descricao AS DESCRICAO_ITEM, 
      grupo_estoque.descricao as GRUPO_DE_ESTOQUE, 
      subgrupo_estoque.descricao as SUBGRUPO_DE_ESTOQUE, 
      GRUPO_ESTOQUE.SEQ_EXIBICAO AS GRUPO_ESTOQUE_SEQ_EXIBICAO, 
      familia_comercial.descricao as FAM_COMERCIAL, 
      familia_industrial.descricao as FAM_INDUSTRIAL, 
      representante.cod_repres as COD_REPRES, 
      representante.razao as RAZAO_REPRES, 
      representante.fantasia as FANTASIA_REPRES, 
      representante.email as EMAIL_REPRES, 
      item_notafiscal.sequencia as SEQUENCIA, 
      item_notafiscal.quantidade AS QTDE, 
      item_notafiscal.valor_unitario AS VLR_UNITARIO, 
      (
        item_notafiscal.quantidade * item_notafiscal.valor_unitario
      ) as VALOR_MERCADORIA, 
      item_notafiscal.perc_descto AS PERC_DESCONTO, 
      item_notafiscal.valor_descto as VALOR_DESCTO, 
      (
        item_notafiscal.valor_total + item_notafiscal.valor_frete
      ) as VALOR_TOTAL 
    from 
      nota_fiscal 
      inner join item_notafiscal on (
        item_notafiscal.cod_empresa = nota_fiscal.cod_empresa 
        and item_notafiscal.serie = nota_fiscal.serie 
        and item_notafiscal.cod_clifor = nota_fiscal.cod_clifor 
        and item_notafiscal.nro_nfiscal = nota_fiscal.nro_nfiscal
      ) 
      inner join clifor on clifor.cod_clifor = nota_fiscal.cod_clifor 
      inner join representante on representante.cod_repres = nota_fiscal.cod_repres 
      inner join cidade on cidade.cod_cidade = clifor.cod_cidade 
      inner join estado on estado.cod_estado = clifor.cod_estado 
      inner join item on item.cod_item = item_notafiscal.cod_item 
      inner join grupo_estoque on grupo_estoque.cod_grupoestoque = item.cod_grupoestoque 
      inner join familia_comercial on familia_comercial.cod_fmcomercial = item.cod_fmcomercial 
      left join grupo_cliente on clifor.cod_grpcliente = grupo_cliente.cod_grpcliente 
      left join repres_comissao on repres_comissao.cod_clifor = clifor.cod_clifor 
      left join representante ve on ve.cod_repres = repres_comissao.cod_repres 
      left join subgrupo_estoque on (
        subgrupo_estoque.cod_grupoestoque = item.cod_grupoestoque 
        and subgrupo_estoque.cod_subgrupoestoque = item.cod_subgrupoestoque
      ) 
      left join familia_industrial on familia_industrial.cod_fmindustrial = item.cod_fmindustrial 
    where 
      nota_fiscal.cod_empresa = '101' 
      and nota_fiscal.situacao <> 'C' 
      and nota_fiscal.dt_emissao between '2024-10-01' and '2024-12-19' 
      and nota_fiscal.entrada_saida = 'S' 
      and item_notafiscal.cod_tiponatureza = '008' 
    union all 
    select 
      nota_fiscal.dt_emissao as DATA_DE_EMISSAO, 
      clifor.dt_cadastro as DATA_CADASTRO, 
      nota_fiscal.nro_nfiscal as NRO_NOTA_FISCAL, 
      nota_fiscal.cod_clifor as CODIGO_CLIENTE, 
      clifor.razao as RAZAO_SOCIAL, 
      clifor.agente_regularanp as AGENTE_REGULARANP, 
      cidade.descricao as MUNICIPIO, 
      estado.descricao as ESTADO, 
      clifor.cod_estado as UF, 
      grupo_cliente.descricao as GRUPO_CLIENTE, 
      item.codigo AS CODIGO_ITEM, 
      item.descricao AS DESCRICAO_ITEM, 
      grupo_estoque.descricao as GRUPO_DE_ESTOQUE, 
      subgrupo_estoque.descricao as SUBGRUPO_DE_ESTOQUE, 
      GRUPO_ESTOQUE.SEQ_EXIBICAO AS GRUPO_ESTOQUE_SEQ_EXIBICAO, 
      familia_comercial.descricao as FAM_COMERCIAL, 
      familia_industrial.descricao as FAM_INDUSTRIAL, 
      representante.cod_repres as COD_REPRES, 
      representante.razao as RAZAO_REPRES, 
      representante.fantasia as FANTASIA_REPRES, 
      representante.email as EMAIL_REPRES, 
      item_notafiscal.sequencia as SEQUENCIA, 
      item_notafiscal.quantidade *-1 AS QTDE, 
      item_notafiscal.valor_unitario AS VLR_UNITARIO, 
      (
        item_notafiscal.quantidade * item_notafiscal.valor_unitario
      ) as VALOR_MERCADORIA, 
      item_notafiscal.perc_descto AS PERC_DESCONTO, 
      (item_notafiscal.valor_descto - 1) as VALOR_DESCTO, 
      (
        (
          item_notafiscal.valor_total + item_notafiscal.valor_frete
        )*-1
      ) as VALOR_TOTAL 
    from 
      nota_fiscal 
      inner join item_notafiscal on (
        item_notafiscal.cod_empresa = nota_fiscal.cod_empresa 
        and item_notafiscal.serie = nota_fiscal.serie 
        and item_notafiscal.cod_clifor = nota_fiscal.cod_clifor 
        and item_notafiscal.nro_nfiscal = nota_fiscal.nro_nfiscal
      ) 
      inner join clifor on clifor.cod_clifor = nota_fiscal.cod_clifor 
      inner join representante on representante.cod_repres = nota_fiscal.cod_repres 
      inner join cidade on cidade.cod_cidade = clifor.cod_cidade 
      inner join estado on estado.cod_estado = clifor.cod_estado 
      inner join item on item.cod_item = item_notafiscal.cod_item 
      inner join grupo_estoque on grupo_estoque.cod_grupoestoque = item.cod_grupoestoque 
      inner join familia_comercial on familia_comercial.cod_fmcomercial = item.cod_fmcomercial 
      left join grupo_cliente on clifor.cod_grpcliente = grupo_cliente.cod_grpcliente 
      left join repres_comissao on repres_comissao.cod_clifor = clifor.cod_clifor 
      left join representante ve on ve.cod_repres = repres_comissao.cod_repres 
      left join subgrupo_estoque on (
        subgrupo_estoque.cod_grupoestoque = item.cod_grupoestoque 
        and subgrupo_estoque.cod_subgrupoestoque = item.cod_subgrupoestoque
      ) 
      left join familia_industrial on familia_industrial.cod_fmindustrial = item.cod_fmindustrial 
    where 
      nota_fiscal.cod_empresa = '101' 
      and nota_fiscal.situacao <> 'C' 
      and nota_fiscal.dt_emissao between '2024-10-01' and '2024-12-19' 
      and nota_fiscal.entrada_saida = 'E' 
      and item_notafiscal.cod_tiponatureza = '012'
  ) TAB 
group by 
  TAB.DATA_DE_EMISSAO, 
  TAB.DATA_CADASTRO, 
  TAB.NRO_NOTA_FISCAL, 
  TAB.CODIGO_CLIENTE, 
  TAB.RAZAO_SOCIAL, 
  TAB.AGENTE_REGULARANP, 
  TAB.MUNICIPIO, 
  TAB.Estado, 
  TAB.UF, 
  TAB.GRUPO_CLIENTE, 
  TAB.CODIGO_ITEM, 
  TAB.DESCRICAO_ITEM, 
  TAB.COD_REPRES, 
  TAB.SEQUENCIA, 
  TAB.RAZAO_REPRES, 
  TAB.FANTASIA_REPRES, 
  TAB.EMAIL_REPRES, 
  TAB.QTDE, 
  TAB.VALOR_TOTAL 
order by 
  TAB.DATA_DE_EMISSAO, 
  TAB.NRO_NOTA_FISCAL, 
  TAB.SEQUENCIA; 
 
